stages:
  data_ingestion:
    cmd: python src/ml/data_ingestion.py data/raw/data.pkl
    deps:
      - src/ml/data_ingestion.py
      - data/raw/data.pkl
    outs:
      - data/raw/comments.csv

  data_cleaning:
    cmd: python src/ml/data_cleaning.py
    deps:
      - src/ml/data_cleaning.py
      - data/raw/comments.csv
    outs:
      - data/processed/cleaned_comments.csv

  feature_engineering:
    cmd: python src/ml/feature_engineering.py
    deps:
      - src/ml/feature_engineering.py
      - data/processed/cleaned_comments.csv
    outs:
      - data/processed/features.csv
      - data/processed/sentence_embeddings.pt

  train:
    cmd: python src/ml/train.py
    deps:
      - data/processed/features.csv
      - src/ml/train.py
      - params.yaml
    outs:
      - models/model.pkl
      - models/encoder.pkl

  promote_model:
    cmd: python src/ml/promote_model.py
    deps:
      - src/ml/promote_model.py
      - params.yaml
      