
feature_engineering:
  embedding_model: "all-MiniLM-L6-v2"  # Pre-trained sentence transformer model

model:
  type: 'sklearn' #sklearn, xgboost, lightgbm, catboost
  name: 'Logistic Regression'
  class: 'LogisticRegression'  # Explicit class name
  params:  # Parameters as a dictionary
    C: 1.0
    max_iter: 1000
    penalty: "l2"
    weight: 'balanced'
