
feature_engineering:
  embedding_model: "all-MiniLM-L6-v2"  # Pre-trained sentence transformer model

model:
  type: 'sklearn' #sklearn, xgboost, lightgbm, catboost
  name: 'Random Forest'
  ModelWithParam: RandomForestClassifier(n_estimators=400, criterion='gini')
