name: MLOps Pipeline
on: [push]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Your local runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true  # For DVC

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure DVC
        run: |
          dvc pull -r myremote

      - name: Run Pipeline
        run: |
          dvc repro
          dvc push -r myremote
